<?php if ($flash['success']) : ?>
    <div class="alert alert-success" role="alert">
        <?php foreach ($flash['success'] as $message) {
            echo $message . '<br>';
        }
        ?>
    </div>
<?php endif; ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1><?= $url['name'] ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $url['id'] ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $url['name'] ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $url['created_at'] ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/1/checks">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
        </table>
    </div>
</main>